language: minimal

services:
  - docker

jobs:
  include:
    - stage: "Test"
      if: type = pull_request
      script:
        - make test
    - stage: "Test & Publish"
      if: (branch = master OR branch = kistler) AND type != pull_request
      script:
        - make test
        - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - make push
